$(document).ready(function(){
    $("#cargarCentro").click(function(){
        $("#contenido").load("index.php/Centro");
    });
    $("#cargarCiclo").click(function(){
        $("#contenido").load("index.php/Ciclo");
    });
    $("#cargarCurso").click(function(){
        $("#contenido").load("index.php/Curso");
    });
    $("#cargarEquipo").click(function(){
        $("#contenido").load("index.php/Equipo");
    });
    $("#cargarEquipo_usuario").click(function(){
        $("#contenido").load("index.php/Equipo_Usuario");
    });
     $("#cargarModulo").click(function(){
        $("#contenido").load("index.php/Modulo");
    });
     $("#cargarReto").click(function(){
        $("#contenido").load("index.php/Reto");
    });
     $("#cargarReto_modulo").click(function(){
        $("#contenido").load("index.php/Reto_Modulo");
    });
     $("#cargarTUsuario").click(function(){
        $("#contenido").load("index.php/TUsuario");
    });
      $("#cargarUsuario").click(function(){
        $("#contenido").load("index.php/Usuario");
    });
      $("#cargarCompetencia").click(function(){
        $("#contenido").load("index.php/Competencia");
    });
      $("#cargarMedicion").click(function(){
        $("#contenido").load("index.php/Medicion");
    });
});
